name: Build KernelSU Module

on:
  push:
    branches: [main, master]
    tags: ['v*']
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: oukaromanager-module
        path: 'module/'
        retention-days: 30
